spring.application.name=Eat_Club
spring.datasource.url=jdbc:postgresql://localhost:5432/Eatclub
spring.datasource.username=postgres
spring.datasource.password=N@agaraju2906
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
